const mockCities = [
  {
    city: 'Munich',
    country: 'de',
    localized_country_name: 'Germany',
    name_string: 'Munich, Germany',
    zip: 'meetup3',
    lat: 48.14,
    lon: 11.58
  },
  {
    city: 'Munich',
    country: 'us',
    localized_country_name: 'USA',
    state: 'ND',
    name_string: 'Munich, North Dakota, USA',
    zip: '58352',
    lat: 48.66,
    lon: -98.85
  }
];

const mockEvents = [
  {
    created: 1554400169000,
    duration: 7200000,
    id: '260347311',
    name: 'Machine Learning (ML) Basics - Erstellung eines ML Modells',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1556613000000,
    local_date: '2019-04-30',
    local_time: '10:30',
    updated: 1554400900000,
    utc_offset: 7200000,
    waitlist_count: 0,
    yes_rsvp_count: 76,
    venue: {
      id: 26170566,
      name: 'WebEx / Watson IoT Center Munich (Eventbrite registration necessary)',
      lat: 48.176448822021484,
      lon: 11.592610359191895,
      repinned: true,
      address_1: 'Mies-van-der-Rohe-Straße 6',
      city: 'München',
      country: 'de',
      localized_country_name: 'Germany'
    },
    group: {
      created: 1400181332000,
      name: 'Big Data Developers in Munich',
      id: 14476282,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Big-Data-Developers-in-Munich',
      who: 'Members',
      localized_location: 'München, Germany',
      state: '',
      country: 'de',
      region: 'en_US',
      timezone: 'Europe/Berlin'
    },
    link: 'https://www.meetup.com/Big-Data-Developers-in-Munich/events/260347311/',
    description: '<p>Sprecher: Alexander Richthammer, Technical Specialist Data Science</p> <p>Im 7. Roundtable dreht sich alles um die Grundlagen und Best Practices der Erstellung eines Machine Learning Modells. Worauf muss man bei der Modellerstellung achten? Was kann ein ML Modell überhaupt leisten? Und was nicht. Was zeichnet ein gutes ML Modell aus? Was sind die Gütekriterien? Warum ist zum Beispiel die Gesamtgenauigkeit ein "irreführendes Konzept"? Diese und weitere Fragen werden im Meetup adressiert. Kurzum: Es geht um die Essenz, was bei der Modellerstellung wirklich wichtig ist. In einer Live-Demo werden schließlich die verschiedenen Möglichkeiten der Modellbildung in Watson Studio aufgezeigt (Notebook, R-Studio, SPSS Modeler, ML Wizard)</p> <p>Agenda<br/>- Was ist Machine Learning?<br/>- Mehrwert von ML Modellen für Unternehmen<br/>- Techniken der Modellierung<br/>- Evaluationskriterien (Accuracy, AUC, Recall etc.)<br/>- Live Demo Watson Studio</p> <p>Teilnahme:<br/>Für eine Vor-Ort-Teilnahme ist bis zum 25. April eine Registrierung bei Eventbrite mit vollständigem Namen zwingend notwendig: <a href="https://www.eventbrite.de/e/7-roundtable-machine-learning-ml-basics-erstellung-eines-ml-modells-tickets-59905026547" class="linkified">https://www.eventbrite.de/e/7-roundtable-machine-learning-ml-basics-erstellung-eines-ml-modells-tickets-59905026547</a></p> <p>Teilnahme remote via WebEx erfordert keine Registrierung bei Eventbrite: <a href="https://ibm.webex.com/meet/schneider" class="linkified">https://ibm.webex.com/meet/schneider</a></p> <p>Für Vor-Ort-Teilnehmer bietet sich nach der Session die Gelegenheit zum persönlichen Austausch und Networking in ungezwungener Atmosphäre, bei einem kleinen Imbiss und Getränken.</p> <p>FAQs:<br/>Wie kann ich den Organisator kontaktieren, wenn ich Fragen habe?<br/>Du kannst mich gerne direkt über meine Mailadresse [masked] kontaktieren.</p> <p>In welcher Sprache wird die Roundtable durchgeführt?<br/>Die Roundtable wird in deutscher Sprache abgehalten. Ich kann nicht vor Ort kommen.</p> <p>Besteht die Möglichkeit, remote an der Roundtable teilzunehmen? Ja, du kannst dich über folgenden Link ab ca. 10.30 Uhr einwählen: <a href="https://ibm.webex.com/meet/schneider" class="linkified">https://ibm.webex.com/meet/schneider</a></p> ',
    how_to_find_us: 'Vor-Ort (nur nach Registrierung über Eventbrite)\n\nWebEx: https://ibm.webex.com/meet/schneider',
    visibility: 'public',
    pro_is_email_shared: false
  },
  {
    created: 1551887400000,
    duration: 10800000,
    id: '259531870',
    name: 'NEXT\'19 Recap // Intro to Google Anthos  / CI/CD in Google Cloud',
    rsvp_limit: 80,
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1556125200000,
    local_date: '2019-04-24',
    local_time: '19:00',
    updated: 1554840522000,
    utc_offset: 7200000,
    waitlist_count: 28,
    yes_rsvp_count: 80,
    venue: {
      id: 26226474,
      name: 'ConSol Software GmbH',
      lat: 48.1204833984375,
      lon: 11.60252857208252,
      repinned: true,
      address_1: 'St.-Cajetan-Straße 43, ',
      city: 'München',
      country: 'de',
      localized_country_name: 'Germany'
    },
    group: {
      created: 1478266159000,
      name: 'GDG Munich Cloud',
      id: 21038385,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'GDG-munich-cloud',
      who: 'Mitglieder',
      localized_location: 'München, Germany',
      state: '',
      country: 'de',
      region: 'en_US',
      timezone: 'Europe/Berlin'
    },
    link: 'https://www.meetup.com/GDG-munich-cloud/events/259531870/',
    description: '<p>WEEEEEE!!!!</p> <p>The next regular Meetup with Big Thanks to ConSol Software GmbH (<a href="https://dev.consol.de" class="linkified">https://dev.consol.de</a>). We are grateful, that they are providing us with space and food for our upcoming meetup and they are looking for people!</p> <p>As always we are looking for a place to host our Meetup and we are looking for speakers in all topics regarding cloud infrastructure.</p> <p>For this evening we have the following schedule:</p> <p>19:00 Meet &amp; Greet &amp; Pizza<br/>19.30 RECAP NEXT 2019<br/>19.45 - Intro to Google Anthos - the multicloud manager - David das Neves - Google Cloud Program Manager<br/>20.15 - CI / CD nativ in Google Cloud - Mario Fahlandt Königspunkt GmbH</p> <p>I\'m looking forward to see you!</p> ',
    visibility: 'public',
    pro_is_email_shared: false
  },
  {
    created: 1552599828000,
    duration: 10800000,
    id: '259772576',
    name: 'Codefin, or a Theory of Relativity for Software Development',
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1555434000000,
    local_date: '2019-04-16',
    local_time: '19:00',
    updated: 1552941195000,
    utc_offset: 7200000,
    waitlist_count: 0,
    yes_rsvp_count: 119,
    venue: {
      id: 26082467,
      name: 'codecentric AG',
      lat: 48.13685989379883,
      lon: 11.523862838745117,
      repinned: true,
      address_1: 'Elsenheimerstraße 55A',
      city: 'München',
      country: 'de',
      localized_country_name: 'Germany'
    },
    group: {
      created: 1411685347000,
      name: 'Munich Software Craft Community',
      id: 17214922,
      join_mode: 'approval',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'munich-software-craft-community',
      who: 'Software Crafters',
      localized_location: 'München, Germany',
      state: '',
      country: 'de',
      region: 'en_US',
      timezone: 'Europe/Berlin'
    },
    link: 'https://www.meetup.com/munich-software-craft-community/events/259772576/',
    description: '<p>Do you always do three-week sprints, user stories, pair programming, TDD, or anything really that starts with "we always do ..."? Then chances are you\'re missing out on the bigger picture and are often applying suboptimal methods. So join us on a journey of building a startup, where we\'ll discover how different measures of time, input, value, quality, collaboration, design, testing, delivery and more are applicable given the various situations. Codefin, or a Theory of Relativity for Software Development will help you become more situationally aware and let you choose practices that are relevant and effective instead of selling you ill-suited silver-bullets.</p> <p>Codefin (<a href="https://codefin.org" class="linkified">https://codefin.org</a>) is about applying the Cynefin sense making framework to specific practices of software development, to e.g. methodology, architecture and design, testing practices, and more. With this approach we bridge over a gap, for Cynefin is mostly used for strategic decisions, while software developers often choose habitually their favourite tools, irrespectively of the context. The resulting Codefin framework is a synergy, where the various methods and practices of software development each find their place in the Cynefin domain landscape, and it becomes clear why the multitude came about and what is the best choice in a given situation.</p> <p>The Cynefin framework (<a href="https://en.wikipedia.org/wiki/Cynefin_framework" class="linkified">https://en.wikipedia.org/wiki/Cynefin_framework</a>) supports the process of making decisions by describing a context using five domains: Disorder, Chaos, Complex, Complicated and Obvious. The framework characterises each of the domains and recommends suitable strategies for dealing with the challenges. The resulting understanding of the situation is a key enabler of good decisions, and for this reason Cynefin is widely used by leaders and in management roles for strategic decisions. However, it can also be eminently applied to software development, thereby helping programmers make sense of all the various approaches to design, architecture, testing, methodologies and beyond.</p> <p>Those who attended the first talk on Codefin may be delighted that we shall continue where we finished our journey in 2017, building upon and extending the original, anchoring the learnings into the development cycle of a new startup, from inception to operation. Those who haven\'t heard of Codefin or Cynefin may be relieved that this talk somehow magically manages to build on both without assuming or requiring prior exposure to said topics. And those in Munich may be especially pleased that extra care has been taken in response to the gentleman in Munich, who wished to had heard more about the non-decisions we\'re accustomed to make habitually. In short: all are invited!</p> <p>Géza is a seasoned software artisan who believes that culture is at the heart of most things. Accordingly, besides practicing the fine art of intuiting, inventing, architecting, designing and crafting code, he also pays attention to foster the growth of his colleagues. At work creating the financial products and services of the future, he gets his kicks from learning from and with like-minded thinkers and tinkerers. He is the founder of the Software Craftsmanship community Coders Only (<a href="https://zurich.codersonly.org" class="linkified">https://zurich.codersonly.org</a>), organising and facilitating events such as the Global Day of Coderetreat and SoCraTes Day Switzerland. He can be found on Twitter with annually changing avatars as @infinitary (<a href="https://twitter.com/infinitary" class="linkified">https://twitter.com/infinitary</a>).</p> <p>Agenda:<br/>19:00 Pizza &amp; Networking<br/>19:30 Talk<br/>Afterwards Discussion</p> ',
    visibility: 'public'
  },
  {
    created: 1554728176000,
    duration: 10800000,
    id: '260445923',
    name: 'Kotlin Users Group Meetup May',
    rsvp_limit: 90,
    date_in_series_pattern: false,
    status: 'upcoming',
    time: 1557161100000,
    local_date: '2019-05-06',
    local_time: '18:45',
    rsvp_close_offset: 'PT44H',
    updated: 1554978288000,
    utc_offset: 7200000,
    waitlist_count: 1,
    yes_rsvp_count: 90,
    venue: {
      id: 26112492,
      name: 'Google',
      lat: 48.143035888671875,
      lon: 11.541084289550781,
      repinned: true,
      address_1: 'Erika-Mann-Straße 33',
      city: 'München',
      country: 'de',
      localized_country_name: 'Germany'
    },
    group: {
      created: 1421043158000,
      name: 'Kotlin User Group Munich - KUG Munich',
      id: 18325305,
      join_mode: 'open',
      lat: 48.13999938964844,
      lon: 11.579999923706055,
      urlname: 'Kotlin-User-Group-Munich',
      who: 'KUG-Hacker',
      localized_location: 'München, Germany',
      state: '',
      country: 'de',
      region: 'en_US',
      timezone: 'Europe/Berlin'
    },
    link: 'https://www.meetup.com/Kotlin-User-Group-Munich/events/260445923/',
    description: '<p>Hello Kotliners. Join us in our May gathering at Google office.</p> <p>Agenda:</p> <p>19:00 - Opening doors</p> <p>19:15 - Michal Harakal - Kotlin multiplatform roller-coaster ride or how I\'ve rewritten a conference app over the weekend.</p> <p>19.55 - Shagen Ogandzhanian (JetBrains) - Kotlin and JS interop, what\'s next. How to use javascript libraries in Kotlin world</p> <p>20.30 - Leonid Popescu (Payworks) - Hybrid SDKs or how we started with Kotlin/Multiplatform without trashing the existing code base</p> <p>Have you been working on a project with Kotlin? Is there a library you would like to discuss? Do you want to try public speaking?<br/>Message us, come and have fun sharing your Kotlin story!</p> ',
    how_to_find_us: 'We will need the full list of guests to print badges beforehand. RSVP will be closed a few days before to implement it.',
    visibility: 'public'
  }
];

export { mockCities, mockEvents };
